

export const constants = {

    SET_ALERT: 'SET_ALERT',
    REMOVE_ALERT: 'REMOVE_ALERT',

    FAIL: 'FAIL',

    LOGIN_REGISTER_SUCCESS: 'LOGIN_REGISTER_SUCCESS',
    LOGOUT: 'LOGOUT',

    GET_LOGGED_USER_SUCCESS: 'GET_LOGGED_USER_SUCCESS'
}