

export const constants = {

    SET_ALERT: 'SET_ALERT',
    REMOVE_ALERT: 'REMOVE_ALERT',

    FAIL: 'FAIL',

    LOGIN_REGISTER_SUCCESS: 'LOGIN_REGISTER_SUCCESS',
    LOGOUT: 'LOGOUT',

    GET_LOGGED_USER_SUCCESS: 'GET_LOGGED_USER_SUCCESS',
    GET_CALENDARS_OF_LOGGED_USER: 'GET_CALENDARS_OF_LOGGED_USER',

    CREATE_CALENDAR_SUCCESS: 'CREATE_CALENDAR_SUCCESS',
    GET_CALENDAR_BY_ID_SUCCESS: 'GET_CALENDAR_BY_ID_SUCCESS',
    UPDATE_CALENDAR_LEGEND_DAY_SUCCESS: 'UPDATE_CALENDAR_LEGEND_DAY_SUCCESS',
    DELETE_SUCCESS: 'DELETE_SUCCESS',

    RESET: 'RESET',
    CALENDAR_RESET: 'CALENDAR_RESET',

    SET_LEGEND: 'SET_LEGEND'

}